[package]
name = "chapter_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = { version = "0.9.3" }
ggegui = { version = "0.3.8" }
specs = { version = "0.20.0" }